### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by tryallthethings** [m66n/flexfieldcontrollib#10]
Hello there!
Thank you for this project! I've been using the IPAddressControl nuGet package for some time now. Since I got back to my project I checked if there was a new version available. Since the nuGet package seems to be gone / not maintained anymore I ultimately ended up here.
This project has currently no license. Can I use it in my project?

Regards
Stefan

**Comment by m66n** [comment]
There's a license file at _flexfieldcontrollib/flexfieldcontrollib/LICENSE_. This project is under the [MIT License](https://en.wikipedia.org/wiki/MIT_License), and you're free to use the code with virtually no limitations. The [`ipaddresscontrollib`](https://github.com/m66n/ipaddresscontrollib) project is also under the MIT License.

I gave up on NuGet because I don't think it's implemented well. It seems that I would have to build a DLL assembly for every available .Net runtime version, instead of NuGet downloading the source and building it with whatever runtime a project was using.

**Comment by tryallthethings** [comment]
Thank you! I didn't check the subfolders for the license - only the root project.
